Homework_11.09 Task - Currying Kvachev George
Cialyni/SPbU_python pull request #13
Opened 2023-10-09 21:32 UTC by Cialyni

2023-10-12 17:12 UTC, toadharvard requested changes

2023-10-12 17:12 UTC, toadharvard commented on src/Homeworks/Homework_11.10/Currying.py
> +    sys.exit()
Если ты делаешь бибилотеку, то sys.exit() на ошибку ввода вызывать очень плохо.
Почитай про exceptions

2023-10-12 17:12 UTC, toadharvard commented on src/Homeworks/Homework_11.10/Currying.py
> +    def curried(*args):
Почему здесь wraps не исрользуешь как ниже?

2023-10-12 17:12 UTC, toadharvard commented on src/Homeworks/Homework_11.10/Currying.py
> +        return reduce(lambda x, y: x(y), args, function)
Прикольно

2023-10-16 19:56 UTC, toadharvard approved these changes

2023-10-17 09:43 UTC, SpirinEgor requested changes

2023-10-17 09:43 UTC, SpirinEgor commented on src/Homeworks/Homework_11.10/Currying.py
> +            "the arity"
Какое-то странное разделение на строки, тут можно красиво в 2 строки записать

2023-10-17 09:43 UTC, SpirinEgor commented on src/Homeworks/Homework_11.10/Currying.py
> +        return lambda *args2: curried(*(args + args2))
- Не уверен, что лямбды здесь уместны 🤔 Но мб и вкусовщина
- Почему args2 кортеж? Мы же каррируем и ожидаем только 1 новый аргумент, который надо добавить к листу (тут еще можно задуматься об эффективном использовании памяти и не плодить кучу листов)

2023-10-17 09:43 UTC, SpirinEgor commented on src/Homeworks/Homework_11.10/Currying.py
> +    return _
Ну это плохо, `_` в качестве имени используется если хотим показать, что это лишнее и надо выкинуть.
Например, хотим распаковать кортеж и оставить только второй элемент: `_, x = point`. А у тебя получается, что ты это дальше используешь в качестве валидной переменной

2023-10-17 09:43 UTC, SpirinEgor commented on src/Homeworks/Homework_11.10/Currying.py
> +        return reduce(lambda x, y: x(y), args, function)
Ага, красивое решение

2023-10-19 13:26 UTC, SpirinEgor approved these changes

2023-10-19 13:26 UTC, merged