Homework 18.10 Task 2 Kvachev
Cialyni/SPbU_python pull request #17
Opened 2023-10-14 23:09 UTC by Cialyni

2023-10-28 11:05 UTC, toadharvard requested changes
Честно, очень плохо читается, я не понимаю, за что отвечает и половина констант в этом решении. Более того, ты полагаешься на формат ввода пользователя, не покрывая и половины случаев.

Разбей еще сильнее на функции. Получай на вход лишь float, а не строку и обрабатывай уже float.

2023-10-28 11:05 UTC, toadharvard commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +    int_part, fraction_part = list(map(int, x.split(".")))
кто сказал, что float c .?

2023-10-28 11:05 UTC, toadharvard commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +    a = input()
введу abc, что делать будешь?

2023-10-28 11:05 UTC, toadharvard commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +def to_exponential(bin_x):
опять полагаешься на строки вида a.b
отсюда очень слабая читаемость и магические тройки по всех функциях

2023-10-28 11:52 UTC, Cialyni commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +def to_exponential(bin_x):
блин, смотрю свой код спустя 2 недели и сам ничего не понимаю)

2023-10-29 22:14 UTC, toadharvard requested changes

2023-10-29 22:14 UTC, toadharvard commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +    int_part, fraction_part = list(map(int, str(x).split(".")))
Ты меня не услышал. Кто тебе сказал, что там вообще есть "."?
float(1e-123)

Получай через арифметику int, fraction

2023-10-29 22:14 UTC, toadharvard commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +    if not x:
Что за случай?

2023-10-29 22:14 UTC, toadharvard commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +def to_exponential(bin_x):
> блин, смотрю свой код спустя 2 недели и сам ничего не понимаю)

намекает как бы)

2023-10-29 22:14 UTC, toadharvard commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +    while dot_ind != 1:  # swap:  123.45 -> 12.345 -> 1.2345 -> .12345
Зачем? Ты знаешь куда переместить ., потому что знаешь индекс. И знаешь сколько периодов там, т.к знаешь индекс.

2023-10-29 22:14 UTC, toadharvard commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +        new_x += x[3 + i]
Три (3), что 3.

2023-10-29 22:14 UTC, toadharvard commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +    for i in range(min(len(x) - 7 - period, m)):
Семь (7), что 7?

2023-10-29 22:14 UTC, toadharvard commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +        new_x += x[period + 3 + i]
Три (3), что 3?

2023-11-15 00:12 UTC, Arsene-Baitenov requested changes
Задание не доделано

2023-11-15 00:12 UTC, Arsene-Baitenov commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +        bin_a = float_to_binary(a)
названия функций не должны зависеть от названий переменных

2023-11-15 00:12 UTC, Arsene-Baitenov commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +def to_exponential(bin_x):
![image](https://github.com/Cialyni/SPbU_python/assets/91395485/12da5083-4f0e-4d9f-a31f-80fd6a847194)

2023-11-15 00:12 UTC, Arsene-Baitenov commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +def to_exponential(bin_x):
некорректный ответ для 0

2023-11-15 00:12 UTC, Arsene-Baitenov commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +    while x:
Вероятно именно из-за этого условия при вводе 0 дробная часть приводиться в пустую строку

2023-11-15 00:12 UTC, Arsene-Baitenov commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +        print("Enter number not something else")
По сути некорректное сообщение об ошибке, текст которого предполагает ввод числа

2023-11-15 00:12 UTC, Arsene-Baitenov commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +        new_type_a = type_change(exponential_a)
Точно ли тут необходима переменная `new_type_a`?

2023-11-15 00:12 UTC, Arsene-Baitenov commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +        return un_exponential(x, 5, 10)
По заданию нужно было вывести битовое представление числа в одном из форматов

2023-11-15 00:12 UTC, Arsene-Baitenov commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +        print("Enter number not something else")
Кроме того оно же выпадает при некорректном вводе формата

2023-11-15 00:12 UTC, Arsene-Baitenov commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +    period = int(x.split("^")[-1])
Зачем эта переменная?

2023-11-15 00:12 UTC, Arsene-Baitenov commented on src/Homeworks/Homework_18.10/Floating_numbers.py
> +    return new_x
Непонятно, что делает эта функция и зачем она вообще нужна

2023-11-29 09:27 UTC, SpirinEgor commented
3 проверки прошли, дедлайны позади. Остается только закрыть 🫠

2023-11-29 09:27 UTC, closed without merging