task4: Robot. Kvachev
Cialyni/SPbU_python pull request #37
Opened 2024-03-09 19:47 UTC by Cialyni

![image](https://github.com/Cialyni/SPbU_python/assets/144917849/67584865-54d4-43ca-ab8a-d0e6616abd33)

2024-03-19 14:13 UTC, SpirinEgor requested changes
20000 строк в тесте? Я это даже посмотреть не могу...

2024-03-19 14:13 UTC, SpirinEgor commented on src/LeetCode/leetcode_task4.py
> +    obstacles: Tuple[Tuple[int]],
Почему где-то list, а где-то tuple?

2024-03-19 14:13 UTC, SpirinEgor commented on src/LeetCode/leetcode_task4.py
> +    obstacles = set((a, b) for a, b in obstacles)
А зачем? К тому же можно просто `set(obstacles)`

2024-03-19 14:13 UTC, SpirinEgor commented on src/LeetCode/leetcode_task4.py
> +            )
Хотя бы так:
```python
current_orientation_ind -= 1
current_orientation_ind %= len(move_orientations)
```

Не красиво же он у тебя разбивает на 3 строки 😅

2024-03-19 14:13 UTC, SpirinEgor commented on src/LeetCode/leetcode_task4.py
> +    x, y = current_pos[0], current_pos[1]
```suggestion
    x, y = current_pos
```

2024-03-19 14:13 UTC, SpirinEgor commented on src/LeetCode/leetcode_task4.py
> +            return x - move_orientation[0], y - move_orientation[1]
Выглядит очень странно:
1. Если 1 раз столкнулись, то дальше точно не пойдем и цикл можно заканчивать
2. Странное решение -- попробовать и отменить, кажется лучше проверить и если можно, то сделать

2024-03-23 18:03 UTC, Cialyni commented on src/LeetCode/leetcode_task4.py
> +            return x - move_orientation[0], y - move_orientation[1]
я пробовал сделать лучше, с красивой проверкой бин поиском по препятствиям, но получилось хуже по времени + код выглядел очень криво.

2024-04-01 12:42 UTC, SpirinEgor requested changes

2024-04-01 12:42 UTC, SpirinEgor commented on src/LeetCode/leetcode_task4.py
> +            return x - move_orientation[0], y - move_orientation[1]
Можно и проверять как есть, я именно про саму логику.
У тебя сейчас: "делаю следующий шаг, если он не получился, то делаю шаг обратно"
Я предлагаю: "проверяю можно ли сделать шаг, если да -- делаю"

По факту, у тебя будет другой порядок с ифом просто

2024-04-01 12:42 UTC, SpirinEgor commented on src/LeetCode/leetcode_task4.py
> +            return x - move_orientation[0], y - move_orientation[1]
Кстати, а зачем тут вообще цикл и `k`?

2024-04-11 12:34 UTC, Cialyni commented on src/LeetCode/leetcode_task4.py
> +            return x - move_orientation[0], y - move_orientation[1]
а как иначе отлавливать препятствия?
мы же можем двигаться в любую из четырех сторон, и там в любом месте может быть препятствие. Тогда надо будет перед перемещением найти все препятствия на одной высоте/ширине с роботом и проверить не врежемся ли мы в ближайшее сверху-снизу/слева-справа. У меня есть решение с таким подходом, но оно очень стремное

2024-04-16 09:50 UTC, SpirinEgor commented on src/LeetCode/leetcode_task4.py
> +            return x - move_orientation[0], y - move_orientation[1]
1. `i` из цикла `for i in range(k)` вообще никак не используется
2. Я предлагаю тебе просто порядок действий поменять, мне не нравится, что ты сначала добавляешь, а потом вычитаешь, если что-то пошло не так. Как вариант `if (x + ..., y + ...) in obstacles`. Ну то есть операция с роботом атомарная, мы либо шагнули им, либо нет

2024-05-02 13:28 UTC, SpirinEgor approved these changes

2024-05-02 13:28 UTC, merged