Leet_code_task9
Cialyni/SPbU_python pull request #41
Opened 2024-04-24 10:14 UTC by Cialyni

2024-05-02 13:32 UTC, SpirinEgor requested changes

2024-05-02 13:32 UTC, SpirinEgor commented on src/LeetCode/leet_code_task9.py
> +    ans = [0]
Зачем тут в лист оборачивать?

2024-05-02 13:32 UTC, SpirinEgor commented on src/LeetCode/leet_code_task9.py
> +        )
Кажется нет смысла в одну строчку писать, в итоге криво и не читаемо стало

2024-05-02 13:32 UTC, SpirinEgor commented on src/LeetCode/leet_code_task9.py
> +    return ans[0]
Не очень нравится запись в "глобальную" переменную, кажется аккуратнее было бы в итоге так сделать: `return _traverse(root)`

2024-05-03 09:57 UTC, Cialyni commented on src/LeetCode/leet_code_task9.py
> +    ans = [0]
тут какой то прикол с областью видимости, я, честно говоря, так и не понял. К списку внутренняя функция имеет доступ, а к обычной переменной нет

2024-05-03 10:32 UTC, Cialyni commented on src/LeetCode/leet_code_task9.py
> +    return ans[0]
ну да, но это не сработает с текущей реализацией: удобно, когда _traverse ищет максимальный путь "вниз" от вершины, а не итоговый ответ на ней, иначе придется, поднимаясь на уровень выше, все равно искать максимальный путь вниз для правого и левого ребенка и сравнивать с результатом на них

2024-05-14 16:43 UTC, SpirinEgor approved these changes

2024-05-14 16:43 UTC, merged