First task in 22.09_practice Kvachev
Cialyni/SPbU_python pull request #5
Opened 2023-09-23 14:38 UTC by Cialyni

Возникли заминки, я слегка опоздал, конечно, но я больше чтобы разобраться скинул, а не на проверку/оценку
По идее, после merge должна появиться папка src

2023-10-04 19:45 UTC, toadharvard commented on src/Practices/Practice_22.09/Fractions.py
> +def fraction_normalization(fraction):
Лучше отдельно принять числитель и знаменатель

2023-10-04 19:46 UTC, toadharvard commented on src/Practices/Practice_22.09/Fractions.py
> +def fraction_output(fraction):
Тут и везде непонятно, что за фракшн без чтения main_logic

2023-10-04 19:47 UTC, toadharvard commented on src/Practices/Practice_22.09/Fractions.py
> +            fraction_normalization(fraction)
меняешь внутри функции fraction, а лучше новый создать внутри и вернуть, а тут присвоить новое значение

2023-10-10 17:51 UTC, SpirinEgor requested changes

2023-10-10 17:51 UTC, SpirinEgor commented on src/Practices/Practice_22.09/Fractions.py
> +    return True
❌

2023-10-10 17:51 UTC, SpirinEgor commented on src/Practices/Practice_22.09/Fractions.py
> +def main_logic(n):
Что за главная логика? Надо называть функцию соответственно тому, что она делает

2023-10-10 17:51 UTC, SpirinEgor commented on src/Practices/Practice_22.09/Fractions.py
> +            fraction_normalization(fraction)
Сейчас неявно происходит преобразование листа. Это непонятно и сложно читается другим. Лучше явно писать
```python
fraction = fraction_normalization(numerator, denominator)
```

Ну и заодно нет необходимости лишние листы создавать, передать пару числе всегда проще

2023-10-10 17:51 UTC, SpirinEgor commented on src/Practices/Practice_22.09/Fractions.py
> +        fraction_output(i)
Вместо этого и непонятной функции, лучше использовать join и в один print уместить

2023-10-10 17:51 UTC, SpirinEgor commented on src/Practices/Practice_22.09/Fractions.py
> +    ans = []
Поиск в листе работает за линейно время, при таком решении лучше использовать множества

2023-10-26 13:52 UTC, SpirinEgor approved these changes

2023-10-26 13:52 UTC, SpirinEgor commented on src/Practices/Practice_22.09/Fractions.py
> +    n = int(input())
Промпт можно сразу передавать в инпут

2023-10-26 13:52 UTC, SpirinEgor commented on src/Practices/Practice_22.09/Fractions.py
> +            if not (fraction in ans):
`fraction not in ans`

2023-10-26 13:52 UTC, SpirinEgor commented on src/Practices/Practice_22.09/Fractions.py
> +    return output
Тут можно красиво через map и join

2023-10-26 13:52 UTC, merged