second task in 22.09_practice Kvachev
Cialyni/SPbU_python pull request #6
Opened 2023-09-23 14:42 UTC by Cialyni

2023-10-04 20:01 UTC, toadharvard commented on src/Practices/Practice_22.09/Cows_and_Bulls.py
> +    digit = input()
А если строку передам?

2023-10-04 20:03 UTC, toadharvard commented on src/Practices/Practice_22.09/Cows_and_Bulls.py
> +    my_digit = random.sample(range(10), 4)
Я бы не хардкодил 4, вынести в отдельную переменную будет гуд

2023-10-04 20:06 UTC, toadharvard commented on src/Practices/Practice_22.09/Cows_and_Bulls.py
> +    return cows - bulls, bulls
Во-первых, функция проверки подразумевает boolean ответ. Во-вторых, очень странный подсчет и вывод, так как позже разницу cows - bulls ты принимаешь за cows (см game).

2023-10-04 20:07 UTC, toadharvard requested changes
:)

2023-11-04 10:35 UTC, SpirinEgor approved these changes

2023-11-04 10:43 UTC, toadharvard approved these changes

2023-11-04 10:43 UTC, merged